[package]
name = "mensonrbx/signal"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/MensonRbx/Signal"
authors = ["mensonrbx <mensonrbx@gmail.com>"]
version = "1.0.0"
description = "Signal implementation in Luau with types. Free to use forever."

[dependencies]
